In [30]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
nodes = np.array([2, 0])

In [38]:
# nodes = sorted(nodes)

In [39]:
a[np.ix_(nodes, nodes)]

array([[10,  9],
       [ 6,  5]])

In [40]:
a[np.ix_(nodes, nodes)] += np.array([[1, 2], [3, 4]])

In [42]:
a

array([[ 9,  2,  9],
       [ 4,  5,  6],
       [11,  8, 11]])

In [43]:
np.sum(a, axis=1)

array([20, 15, 30])

In [44]:
b = np.array([2, 3, 1, 4, 5])
b

array([2, 3, 1, 4, 5])

In [45]:
np.argsort(b)

array([2, 0, 1, 3, 4])